// Generated by gencpp from file kalman/vector9.msg
// DO NOT EDIT!


#ifndef KALMAN_MESSAGE_VECTOR9_H
#define KALMAN_MESSAGE_VECTOR9_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kalman
{
template <class ContainerAllocator>
struct vector9_
{
  typedef vector9_<ContainerAllocator> Type;

  vector9_()
    : m1(0.0)
    , m2(0.0)
    , m3(0.0)
    , m4(0.0)
    , m5(0.0)
    , m6(0.0)
    , m7(0.0)
    , m8(0.0)
    , m9(0.0)  {
    }
  vector9_(const ContainerAllocator& _alloc)
    : m1(0.0)
    , m2(0.0)
    , m3(0.0)
    , m4(0.0)
    , m5(0.0)
    , m6(0.0)
    , m7(0.0)
    , m8(0.0)
    , m9(0.0)  {
  (void)_alloc;
    }



   typedef double _m1_type;
  _m1_type m1;

   typedef double _m2_type;
  _m2_type m2;

   typedef double _m3_type;
  _m3_type m3;

   typedef double _m4_type;
  _m4_type m4;

   typedef double _m5_type;
  _m5_type m5;

   typedef double _m6_type;
  _m6_type m6;

   typedef double _m7_type;
  _m7_type m7;

   typedef double _m8_type;
  _m8_type m8;

   typedef double _m9_type;
  _m9_type m9;





  typedef boost::shared_ptr< ::kalman::vector9_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kalman::vector9_<ContainerAllocator> const> ConstPtr;

}; // struct vector9_

typedef ::kalman::vector9_<std::allocator<void> > vector9;

typedef boost::shared_ptr< ::kalman::vector9 > vector9Ptr;
typedef boost::shared_ptr< ::kalman::vector9 const> vector9ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kalman::vector9_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kalman::vector9_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kalman

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'kalman': ['/home/rajat/rajat_ws/src/kalman/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kalman::vector9_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kalman::vector9_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kalman::vector9_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kalman::vector9_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman::vector9_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman::vector9_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kalman::vector9_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13d161e27dab4d6e323137aa0417c879";
  }

  static const char* value(const ::kalman::vector9_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13d161e27dab4d6eULL;
  static const uint64_t static_value2 = 0x323137aa0417c879ULL;
};

template<class ContainerAllocator>
struct DataType< ::kalman::vector9_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kalman/vector9";
  }

  static const char* value(const ::kalman::vector9_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kalman::vector9_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 m1\n\
float64 m2\n\
float64 m3\n\
float64 m4\n\
float64 m5\n\
float64 m6\n\
float64 m7\n\
float64 m8\n\
float64 m9\n\
";
  }

  static const char* value(const ::kalman::vector9_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kalman::vector9_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m1);
      stream.next(m.m2);
      stream.next(m.m3);
      stream.next(m.m4);
      stream.next(m.m5);
      stream.next(m.m6);
      stream.next(m.m7);
      stream.next(m.m8);
      stream.next(m.m9);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vector9_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kalman::vector9_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kalman::vector9_<ContainerAllocator>& v)
  {
    s << indent << "m1: ";
    Printer<double>::stream(s, indent + "  ", v.m1);
    s << indent << "m2: ";
    Printer<double>::stream(s, indent + "  ", v.m2);
    s << indent << "m3: ";
    Printer<double>::stream(s, indent + "  ", v.m3);
    s << indent << "m4: ";
    Printer<double>::stream(s, indent + "  ", v.m4);
    s << indent << "m5: ";
    Printer<double>::stream(s, indent + "  ", v.m5);
    s << indent << "m6: ";
    Printer<double>::stream(s, indent + "  ", v.m6);
    s << indent << "m7: ";
    Printer<double>::stream(s, indent + "  ", v.m7);
    s << indent << "m8: ";
    Printer<double>::stream(s, indent + "  ", v.m8);
    s << indent << "m9: ";
    Printer<double>::stream(s, indent + "  ", v.m9);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KALMAN_MESSAGE_VECTOR9_H
