# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kalman/matrix6.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import kalman.msg
import std_msgs.msg

class matrix6(genpy.Message):
  _md5sum = "699fb7d217df09274ee066bff5a81e6d"
  _type = "kalman/matrix6"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

vector9 r1
vector9 r2
vector9 r3
vector9 r4
vector9 r5
vector9 r6

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: kalman/vector9
float64 m1
float64 m2
float64 m3
float64 m4
float64 m5
float64 m6
float64 m7
float64 m8
float64 m9
"""
  __slots__ = ['header','r1','r2','r3','r4','r5','r6']
  _slot_types = ['std_msgs/Header','kalman/vector9','kalman/vector9','kalman/vector9','kalman/vector9','kalman/vector9','kalman/vector9']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,r1,r2,r3,r4,r5,r6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(matrix6, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.r1 is None:
        self.r1 = kalman.msg.vector9()
      if self.r2 is None:
        self.r2 = kalman.msg.vector9()
      if self.r3 is None:
        self.r3 = kalman.msg.vector9()
      if self.r4 is None:
        self.r4 = kalman.msg.vector9()
      if self.r5 is None:
        self.r5 = kalman.msg.vector9()
      if self.r6 is None:
        self.r6 = kalman.msg.vector9()
    else:
      self.header = std_msgs.msg.Header()
      self.r1 = kalman.msg.vector9()
      self.r2 = kalman.msg.vector9()
      self.r3 = kalman.msg.vector9()
      self.r4 = kalman.msg.vector9()
      self.r5 = kalman.msg.vector9()
      self.r6 = kalman.msg.vector9()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_54d().pack(_x.r1.m1, _x.r1.m2, _x.r1.m3, _x.r1.m4, _x.r1.m5, _x.r1.m6, _x.r1.m7, _x.r1.m8, _x.r1.m9, _x.r2.m1, _x.r2.m2, _x.r2.m3, _x.r2.m4, _x.r2.m5, _x.r2.m6, _x.r2.m7, _x.r2.m8, _x.r2.m9, _x.r3.m1, _x.r3.m2, _x.r3.m3, _x.r3.m4, _x.r3.m5, _x.r3.m6, _x.r3.m7, _x.r3.m8, _x.r3.m9, _x.r4.m1, _x.r4.m2, _x.r4.m3, _x.r4.m4, _x.r4.m5, _x.r4.m6, _x.r4.m7, _x.r4.m8, _x.r4.m9, _x.r5.m1, _x.r5.m2, _x.r5.m3, _x.r5.m4, _x.r5.m5, _x.r5.m6, _x.r5.m7, _x.r5.m8, _x.r5.m9, _x.r6.m1, _x.r6.m2, _x.r6.m3, _x.r6.m4, _x.r6.m5, _x.r6.m6, _x.r6.m7, _x.r6.m8, _x.r6.m9))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.r1 is None:
        self.r1 = kalman.msg.vector9()
      if self.r2 is None:
        self.r2 = kalman.msg.vector9()
      if self.r3 is None:
        self.r3 = kalman.msg.vector9()
      if self.r4 is None:
        self.r4 = kalman.msg.vector9()
      if self.r5 is None:
        self.r5 = kalman.msg.vector9()
      if self.r6 is None:
        self.r6 = kalman.msg.vector9()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 432
      (_x.r1.m1, _x.r1.m2, _x.r1.m3, _x.r1.m4, _x.r1.m5, _x.r1.m6, _x.r1.m7, _x.r1.m8, _x.r1.m9, _x.r2.m1, _x.r2.m2, _x.r2.m3, _x.r2.m4, _x.r2.m5, _x.r2.m6, _x.r2.m7, _x.r2.m8, _x.r2.m9, _x.r3.m1, _x.r3.m2, _x.r3.m3, _x.r3.m4, _x.r3.m5, _x.r3.m6, _x.r3.m7, _x.r3.m8, _x.r3.m9, _x.r4.m1, _x.r4.m2, _x.r4.m3, _x.r4.m4, _x.r4.m5, _x.r4.m6, _x.r4.m7, _x.r4.m8, _x.r4.m9, _x.r5.m1, _x.r5.m2, _x.r5.m3, _x.r5.m4, _x.r5.m5, _x.r5.m6, _x.r5.m7, _x.r5.m8, _x.r5.m9, _x.r6.m1, _x.r6.m2, _x.r6.m3, _x.r6.m4, _x.r6.m5, _x.r6.m6, _x.r6.m7, _x.r6.m8, _x.r6.m9,) = _get_struct_54d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_54d().pack(_x.r1.m1, _x.r1.m2, _x.r1.m3, _x.r1.m4, _x.r1.m5, _x.r1.m6, _x.r1.m7, _x.r1.m8, _x.r1.m9, _x.r2.m1, _x.r2.m2, _x.r2.m3, _x.r2.m4, _x.r2.m5, _x.r2.m6, _x.r2.m7, _x.r2.m8, _x.r2.m9, _x.r3.m1, _x.r3.m2, _x.r3.m3, _x.r3.m4, _x.r3.m5, _x.r3.m6, _x.r3.m7, _x.r3.m8, _x.r3.m9, _x.r4.m1, _x.r4.m2, _x.r4.m3, _x.r4.m4, _x.r4.m5, _x.r4.m6, _x.r4.m7, _x.r4.m8, _x.r4.m9, _x.r5.m1, _x.r5.m2, _x.r5.m3, _x.r5.m4, _x.r5.m5, _x.r5.m6, _x.r5.m7, _x.r5.m8, _x.r5.m9, _x.r6.m1, _x.r6.m2, _x.r6.m3, _x.r6.m4, _x.r6.m5, _x.r6.m6, _x.r6.m7, _x.r6.m8, _x.r6.m9))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.r1 is None:
        self.r1 = kalman.msg.vector9()
      if self.r2 is None:
        self.r2 = kalman.msg.vector9()
      if self.r3 is None:
        self.r3 = kalman.msg.vector9()
      if self.r4 is None:
        self.r4 = kalman.msg.vector9()
      if self.r5 is None:
        self.r5 = kalman.msg.vector9()
      if self.r6 is None:
        self.r6 = kalman.msg.vector9()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 432
      (_x.r1.m1, _x.r1.m2, _x.r1.m3, _x.r1.m4, _x.r1.m5, _x.r1.m6, _x.r1.m7, _x.r1.m8, _x.r1.m9, _x.r2.m1, _x.r2.m2, _x.r2.m3, _x.r2.m4, _x.r2.m5, _x.r2.m6, _x.r2.m7, _x.r2.m8, _x.r2.m9, _x.r3.m1, _x.r3.m2, _x.r3.m3, _x.r3.m4, _x.r3.m5, _x.r3.m6, _x.r3.m7, _x.r3.m8, _x.r3.m9, _x.r4.m1, _x.r4.m2, _x.r4.m3, _x.r4.m4, _x.r4.m5, _x.r4.m6, _x.r4.m7, _x.r4.m8, _x.r4.m9, _x.r5.m1, _x.r5.m2, _x.r5.m3, _x.r5.m4, _x.r5.m5, _x.r5.m6, _x.r5.m7, _x.r5.m8, _x.r5.m9, _x.r6.m1, _x.r6.m2, _x.r6.m3, _x.r6.m4, _x.r6.m5, _x.r6.m6, _x.r6.m7, _x.r6.m8, _x.r6.m9,) = _get_struct_54d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_54d = None
def _get_struct_54d():
    global _struct_54d
    if _struct_54d is None:
        _struct_54d = struct.Struct("<54d")
    return _struct_54d
