# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kalman/vector6.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class vector6(genpy.Message):
  _md5sum = "b0972f5571e47e4faf8f68d08a868fe1"
  _type = "kalman/vector6"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 m1
float64 m2
float64 m3
float64 m4
float64 m5
float64 m6
"""
  __slots__ = ['m1','m2','m3','m4','m5','m6']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       m1,m2,m3,m4,m5,m6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(vector6, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.m1 is None:
        self.m1 = 0.
      if self.m2 is None:
        self.m2 = 0.
      if self.m3 is None:
        self.m3 = 0.
      if self.m4 is None:
        self.m4 = 0.
      if self.m5 is None:
        self.m5 = 0.
      if self.m6 is None:
        self.m6 = 0.
    else:
      self.m1 = 0.
      self.m2 = 0.
      self.m3 = 0.
      self.m4 = 0.
      self.m5 = 0.
      self.m6 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.m1, _x.m2, _x.m3, _x.m4, _x.m5, _x.m6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.m1, _x.m2, _x.m3, _x.m4, _x.m5, _x.m6,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.m1, _x.m2, _x.m3, _x.m4, _x.m5, _x.m6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.m1, _x.m2, _x.m3, _x.m4, _x.m5, _x.m6,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
